### ISSUE TITLE
Broken apk file

### ISSUE THREAD

**Issue by RoonMoonlight** [javulticat/NewPipe#8]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/javulticat/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/javulticat/NewPipe/issues) or [closed](https://github.com/javulticat/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/javulticat/NewPipe/blob/sponsorblock/.github/CONTRIBUTING.md).

### Affected version

v0.26.1-2

### Steps to reproduce the bug

1. Download v0.26.1-2 from releases page
2. Open apk file and press install
3. "App not installed as package appears to be invalid" displays and refuses to be installed

### Expected behavior

It should be able to install apk file without any problem.

### Actual behavior

It refuses to install

### Screenshots/Screen recordings

<img alt="Screenshot_20240104_214058_Package installer" src="https://github.com/javulticat/NewPipe/assets/25527589/b5d738ad-047b-48b6-b251-7d974693e0ce" width=290 />

### Logs

No logs

### Affected Android/Custom ROM version

Android 14: One UI 6

### Affected device model

Samsung Galaxy S22+

**Comment by Seanld** [comment]
Obtainium tells me

```
Some Errors Occurred

Downloaded package ID does not match existing App ID - com.javulticat.newpipe [NewPipe sponsorblock]
```

Even after completely uninstalling the previous version before installing the new `-2` version.

**Comment by javulticat** [comment]
My fault - shouldn't have uploaded a version at 5AM without manually testing it worked.  I'll take down the release for now.  The dual-edged sword of automation.  :confused:

I noticed that the CI tests that should have caught this are not currently getting run for our default branch (`sponsorblock`), as that branch doesn't exist upstream.  I'm enabling those tests now, which I hope will provide me with further insight into the problem here.  Sorry for the inconvenience!

@Seanld The performance issues are a known issue with the first release (#3), which is why I was in a rush to get `v0.26.1-2` out.  But, thanks for a second confirmation that this is happening with the first release.

Thanks both for your reports!  Working on this now.

**Comment by Seanld** [comment]
Oh I didn't even see that issue. I should have checked the closed issues, but I didn't. Thanks for working to keep this app functional while poly works on their new implementation!
